# Use the standard Nginx image from Docker Hub
FROM nginx

# Author Name
LABEL ANAND VERMA

#Copy to overwrite NGINX configuration
COPY Docker/nginx/nginx.conf /etc/nginx/nginx.conf

#Expose the NGINX container port
EXPOSE 8080