# All comment lines start with #

# Use the standard Nginx image from Docker Hub
FROM nginx:1.15.8-alpine

# Author Name
LABEL ANAND VERMA

#Copy to overwrite NGINX configuration
COPY Docker/nginx/nginx.conf /etc/nginx/nginx.conf

#Expose the NGINX container port. Uncomment below line to expose the port.
#EXPOSE 8080